name: Test Workflow

##specify
on:
  push:
    branches: 
        - main
  workflow_dispatch:

jobs:
  
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: create a file on the runner
        run: mkdir testapp
      - name: display the command 
        run: echo "i am learning github actions"